<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>ddd7484a-287d-4e6e-8e48-7a5eadad677d</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<PublishTrimmed>false</PublishTrimmed>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="AutoRunner.http" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="AutoRunner.http">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Hangfire" Version="1.8.14" />
		<PackageReference Include="Hangfire.AspNetCore" Version="1.8.14" />
		<PackageReference Include="Hangfire.Console.Extensions" Version="2.0.0" />
		<PackageReference Include="Hangfire.Console.Extensions.Serilog" Version="2.0.0" />
		<PackageReference Include="Hangfire.Dashboard.BasicAuthorization" Version="1.0.2" />
		<PackageReference Include="Hangfire.MemoryStorage" Version="1.8.1.2" />
		<PackageReference Include="Hangfire.MissionControl" Version="0.10.0" />
		<PackageReference Include="Hangfire.PostgreSql" Version="1.20.12" />
		<PackageReference Include="Hangfire.RecurringJobExtensions" Version="1.1.6" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Serilog" Version="4.0.1" />
		<PackageReference Include="Serilog.AspNetCore" Version="8.0.2" />
		<PackageReference Include="Serilog.Settings.Configuration" Version="8.0.2" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Controllers\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Clients\IndieGala.Client\IndieGala.Client.csproj" />
	  <ProjectReference Include="..\Clients\SteamGifts.Client\SteamGifts.Client.csproj" />
	  <ProjectReference Include="..\Clients\SteamPowered.Client\SteamPowered.Client.csproj" />
	  <ProjectReference Include="..\Clients\TelegramNotifier.Client\TelegramNotifier.Client.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Content Update="appsettings.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>
</Project>
