name: Build & Deploy to Hetzner (Docker only)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Upload project to server via SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "."
        target: "/opt/autorunner"

    - name: Build and restart container via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
            # папка, где уже есть клон репозитория
            cd /opt/autorunner

            echo "Pull latest changes..."
            git fetch origin master
            git reset --hard origin/master

            echo "Stopping and removing old container (if any)..."
            docker stop autorunner || true
            docker rm autorunner || true

            cd AutoRunner

            echo "Building Docker image..."
            docker build --no-cache -t autorunner:latest .

            echo "Starting new container..."
            docker run -d \
              --name autorunner \
              -e APP_UID=1000 \
              -e ConnectionStrings__DefaultConnection="${{ secrets.DEFAULT_CONNECTION_STRING }}" \
              -e Hangfire__Login="${{ secrets.HANGFIRE_LOGIN }}" \
              -e Hangfire__Password="${{ secrets.HANGFIRE_PASSWORD }}" \
              -p 5000:5000 \
              autorunner:latest